---
kind: Service
apiVersion: v1
metadata:
  name: blog-feed
  namespace: blog
  labels:
    app: blog-feed
spec:
  selector:
    app: blog-feed
  ports:
  - protocol: TCP
    port: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-feed
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-feed
  template:
    metadata:
      labels:
        app: blog-feed
    spec:
      containers:
      - image: ghcr.io/categolj/blog-feed
        name: blog-feed
        ports:
        - containerPort: 8080
        env:
        - name: API_URL
          value: http://blog-rsocket.blog.svc.cluster.local:8080/entries
        - name: ZIPKIN_URL
          value: https://zipkin.dev.ik.am
        - name: PORT
          value: "8080"
        resources:
          limits:
            memory: "32Mi"
          requests:
            memory: "16Mi"