---
kind: Service
apiVersion: v1
metadata:
  name: blog-feed
  namespace: blog
  labels:
    app: blog-feed
spec:
  selector:
    app: blog-feed
  ports:
  - protocol: TCP
    port: 8080
    name: http
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: blog-feed
  namespace: blog
spec:
  serviceName: blog-feed
  route:
    predicates:
    - Host=feed.ik.am
    filters:
    - RequestLogging=
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: feed-rss
  namespace: blog
spec:
  serviceName: blog-feed
  route:
    predicates:
    - Path=/feed,/rss
    filters:
    - RequestLogging=
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: blog-rss
  namespace: blog
spec:
  serviceName: blog-feed
  route:
    predicates:
    - Host=rss.ik.am
    filters:
    - RequestLogging=
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: blog-atom
  namespace: blog
spec:
  serviceName: blog-feed
  route:
    predicates:
    - Host=atom.ik.am
    filters:
    - RequestLogging=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-feed
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-feed
  template:
    metadata:
      labels:
        app: blog-feed
    spec:
      containers:
      - image: making/blog-feed
        name: blog-feed
        ports:
        - containerPort: 8080
        env:
        - name: API_URL
          value: http://blog-rsocket.blog.svc.cluster.local:8080/entries
        - name: ZIPKIN_URL
          value: https://zipkin.dev.ik.am
        - name: PORT
          value: "8080"
        resources:
          limits:
            memory: "32Mi"
          requests:
            memory: "16Mi"