---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: blog-feed
  namespace: blog
spec:
  serviceName: blog-feed
  route:
    predicates:
    - Host=feed.ik.am
    filters:
    - RequestLogging=
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: feed-rss
  namespace: blog
spec:
  serviceName: blog-feed
  route:
    predicates:
    - Path=/feed,/rss
    filters:
    - RequestLogging=
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: blog-rss
  namespace: blog
spec:
  serviceName: blog-feed
  route:
    predicates:
    - Host=rss.ik.am
    filters:
    - RequestLogging=
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: blog-atom
  namespace: blog
spec:
  serviceName: blog-feed
  route:
    predicates:
    - Host=atom.ik.am
    filters:
    - RequestLogging=